package java1005.collection;

import java.util.ArrayList;
import java.util.List;

public class Names {
    private List<Student> studentObjs = new ArrayList<>();


    public List<Student> getStudentObjs() {
        this.studentObjs.add(new Student(1, "권하준", "https://github.com/dongyeon-0822/java-project-exercise"));
        this.studentObjs.add(new Student(1, "조성윤", "https://github.com/kang-subin/Java"));
        this.studentObjs.add(new Student(3, "안예은", "https://github.com/KoKwanwun/LikeLion.git"));
        this.studentObjs.add(new Student(1, "남우빈", "https://github.com/lcomment/Algorithm_Solution--Java/tree/main/LikeLion"));
        this.studentObjs.add(new Student(2, "최경민", "https://github.com/cmkxak/likelion-java-course"));
        return studentObjs;
    }

    public void getName(List<String> students){
        students.add("권하준");
        students.add("조성윤");
        students.add("안예은");
        students.add("남우빈");
        students.add("최경민");
        students.add("안준휘");
        students.add("하채민");
        students.add("허도한");
        students.add("배태훈");
        students.add("정해성");
        students.add("하찬희");
        students.add("박도아");
        students.add("유경준");
        students.add("고다니엘");
        students.add("하이안");
        students.add("고유호");
        students.add("전민찬");
        students.add("배강");
        students.add("유서이");
        students.add("황도빈");
        students.add("강규진");
        students.add("임예린");
        students.add("양예온");
        students.add("곽윤재");
        students.add("한단");
        students.add("박강현");
        students.add("윤성민");
        students.add("박재윤");
        students.add("서현준");
        students.add("노유주");
        students.add("전율");
        students.add("노아린");
        students.add("권아윤");
        students.add("송태서");
        students.add("정라온");
        students.add("서서한");
        students.add("문주호");
        students.add("오세아");
        students.add("이호영");
        students.add("손윤아");
        students.add("이동우");
        students.add("남혜준");
        students.add("황솔 ");
        students.add("권은재");
        students.add("곽준휘");
        students.add("양시현");
        students.add("김지훈");
        students.add("신서아");
        students.add("노도형");
        students.add("허선");
        students.add("노지아");
        students.add("신아인");
        students.add("양시은");
        students.add("노석현");
        students.add("손강준");
        students.add("백주안");
        students.add("강단우");
        students.add("오나은");
        students.add("오한겸");
        students.add("백예준");
        students.add("노은우");
        students.add("손도헌");
        students.add("전진우");
        students.add("안주하");
        students.add("백다은");
        students.add("유민기");
        students.add("노휘 ");
        students.add("박채원");
        students.add("강다겸");
        students.add("신여준");
        students.add("허은유");
        students.add("심서후");
        students.add("유준이");
        students.add("전민승");
        students.add("강예은");
        students.add("허로이");
        students.add("유유진");
        students.add("권건하");
        students.add("하도이");
        students.add("노도원");
        students.add("문하성");
        students.add("오시후");
        students.add("이로윤");
        students.add("노지후");
        students.add("권채이");
        students.add("전담");
        students.add("하태율");
        students.add("노다율");
        students.add("장우솔");
        students.add("황하준");
        students.add("조담호");
        students.add("백민우");
        students.add("김시진");
        students.add("박유담");
        students.add("이해성");
        students.add("전현성");
        students.add("권유겸");
        students.add("강서현");
        students.add("문찬율");
        students.add("한도현");
    }
}
